/**
 * Unit suite for the offline codegen drift check.
 *
 * The fixtures are REAL codegen output — generated by `pipelex codegen types` and
 * vendored verbatim — because the whole point of this module is that a verdict it
 * computes equals the one `pipelex codegen check` computes over the same bytes. A
 * hand-written stamp would only prove the port agrees with itself.
 *
 * The artifacts are vendored with a trailing `.txt` (`types.ts.txt`, `models.py.txt`)
 * and their real names restored at load time. That is not tidiness: `format:check`,
 * `lint`, and `typecheck:test` all glob `tests/**\/*.ts`, and this repo formats at
 * `printWidth: 100` while the ts-zod emitter targets Prettier's 80-column default —
 * so a `.ts` fixture would be reformatted (or reddened for importing `zod`, which is
 * not a dependency here), and a single rewritten byte invalidates the very hash the
 * fixture exists to pin.
 */

import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import {
  CodegenLockError,
  isStampableArtifactPath,
  runCodegenCheck,
  STAMPABLE_ARTIFACT_SUFFIXES,
} from "../src/codegen-check.js";
import type { CodegenCheckInput, CodegenTreeFile } from "../src/codegen-check.js";
import {
  handEdit,
  regenerate,
  splitStamp,
  STAMP_BEGIN,
  STAMP_END,
} from "./helpers/codegen-stamp.js";

// ── Fixtures ─────────────────────────────────────────────────────────────

const FIXTURE_ROOT = new URL("./fixtures/codegen/", import.meta.url);

/** The crate both fixture flavors were projected from — a property of the crate, not the target. */
const CRATE_FINGERPRINT = "e4623057c69e8962796244a035d86e772ffd0231a8f4f6c1a4f31913db3f3c9b";
const ENGINE_VERSION = "0.46.4";

const TS_ARTIFACTS = ["binder.ts", "types.ts"];
const PY_ARTIFACTS = ["models.py"];

function loadFixture(flavor: string, artifactPaths: readonly string[]): CodegenCheckInput {
  return {
    lockContent: readFileSync(new URL(`${flavor}/codegen.lock`, FIXTURE_ROOT), "utf8"),
    files: artifactPaths.map((path) => ({
      path,
      content: readFileSync(new URL(`${flavor}/${path}.txt`, FIXTURE_ROOT), "utf8"),
    })),
  };
}

function tsFixture(): CodegenCheckInput {
  return loadFixture("ts-zod", TS_ARTIFACTS);
}

function pyFixture(): CodegenCheckInput {
  return loadFixture("python-pydantic", PY_ARTIFACTS);
}

// ── Tree mutators ────────────────────────────────────────────────────────

/** The same tree with one file's content replaced. */
function withEdit(
  input: CodegenCheckInput,
  path: string,
  edit: (content: string) => string,
): CodegenCheckInput {
  return {
    ...input,
    files: input.files.map((file) =>
      file.path === path ? { ...file, content: edit(file.content) } : file,
    ),
  };
}

/** The same tree without one file. */
function without(input: CodegenCheckInput, path: string): CodegenCheckInput {
  return { ...input, files: input.files.filter((file) => file.path !== path) };
}

/** The same tree with extra files added. */
function plus(input: CodegenCheckInput, ...extra: CodegenTreeFile[]): CodegenCheckInput {
  return { ...input, files: [...input.files, ...extra] };
}

function contentOf(input: CodegenCheckInput, path: string): string {
  const file = input.files.find((candidate) => candidate.path === path);
  if (file === undefined) {
    throw new Error(`Fixture has no file at '${path}'.`);
  }
  return file.content;
}

/** A minimal hand-written lock, for the malformed-shape cases the real fixtures cannot express. */
function lockWith(body: string): string {
  return `crate_fingerprint = "abc"\nengine_version = "0.0.0"\n\n${body}`;
}

/** One `[[artifacts]]` entry. Takes the QUOTED TOML spelling, so escaping stays explicit. */
function artifactEntry(tomlPath: string): string {
  return `[[artifacts]]\npath = ${tomlPath}\ncontent_hash = "deadbeef"\n`;
}

/**
 * A TOML *literal* string (single quotes, no escape processing).
 *
 * Load-bearing for the path cases: in a basic string `"sub\\types.ts"` TOML reads `\\t`
 * as a TAB, so a "backslash" case written that way would actually be testing the
 * control-character rule.
 */
function tomlLiteral(path: string): string {
  return `'${path}'`;
}

// ── A pristine tree ──────────────────────────────────────────────────────

describe("runCodegenCheck — a pristine tree", () => {
  it("reports the ts-zod fixture current, with no drifts", async () => {
    const report = await runCodegenCheck(tsFixture());

    expect(report.drifts).toEqual([]);
    expect(report.isCurrent).toBe(true);
  });

  it("reports the python fixture current — the `#` comment prefix", async () => {
    const report = await runCodegenCheck(pyFixture());

    expect(report.drifts).toEqual([]);
    expect(report.isCurrent).toBe(true);
  });

  it("surfaces the lock header, so a caller can compare against a live codegen() response", async () => {
    const tsReport = await runCodegenCheck(tsFixture());
    const pyReport = await runCodegenCheck(pyFixture());

    expect(tsReport.crateFingerprint).toBe(CRATE_FINGERPRINT);
    expect(tsReport.engineVersion).toBe(ENGINE_VERSION);
    // The fingerprint is a property of the CRATE, not of the projection: the two
    // targets are different bytes generated from the same resolved crate.
    expect(pyReport.crateFingerprint).toBe(CRATE_FINGERPRINT);
  });
});

// ── The drift taxonomy ───────────────────────────────────────────────────

describe("runCodegenCheck — drift categories", () => {
  it("reports a locked artifact absent from the tree as `missing`", async () => {
    const report = await runCodegenCheck(without(tsFixture(), "types.ts"));

    expect(report.isCurrent).toBe(false);
    expect(report.drifts).toEqual([
      { path: "types.ts", category: "missing", detail: "Locked artifact is absent on disk." },
    ]);
  });

  it("reports a regenerated body whose stamp agrees but whose lock is stale as `modified`", async () => {
    const input = withEdit(tsFixture(), "types.ts", (content) =>
      regenerate(content, "export const NEWER = 1;\n"),
    );

    const report = await runCodegenCheck(input);

    expect(report.drifts).toEqual([
      {
        path: "types.ts",
        category: "modified",
        detail: "Body no longer matches the locked hash — regenerate.",
      },
    ]);
  });

  it("reports an edit below an intact stamp as `hand-edited` — exactly once, never also `modified`", async () => {
    const input = withEdit(tsFixture(), "types.ts", (content) =>
      handEdit(content, "export const HAND = 1;\n"),
    );

    const report = await runCodegenCheck(input);

    // The edit breaks BOTH the stamp hash and the locked hash. Upstream returns on the
    // first, so the report names the hand edit once — the precedence a from-the-prose
    // implementation gets wrong by emitting two drifts.
    expect(report.drifts).toEqual([
      {
        path: "types.ts",
        category: "hand-edited",
        detail: "Body was edited below the stamp (stamp hash no longer matches).",
      },
    ]);
  });

  it("reports a stripped stamp as `hand-edited`", async () => {
    const input = withEdit(tsFixture(), "types.ts", (content) => splitStamp(content).body);

    const report = await runCodegenCheck(input);

    expect(report.drifts).toEqual([
      {
        path: "types.ts",
        category: "hand-edited",
        detail: "Stamp header is missing or unparseable.",
      },
    ]);
  });

  it("reports a stamp with no end marker as `hand-edited`", async () => {
    const input = withEdit(tsFixture(), "types.ts", (content) =>
      content.replace(`// ${STAMP_END}\n`, ""),
    );

    const report = await runCodegenCheck(input);

    expect(report.drifts[0]?.category).toBe("hand-edited");
    expect(report.drifts[0]?.detail).toBe("Stamp header is missing or unparseable.");
  });

  it("does NOT report a CRLF-rewritten tree — the reference reader normalizes newlines", async () => {
    // What `core.autocrlf=true` does to a committed tree on a Windows checkout, and what
    // pipelex itself writes when it runs there. `pipelex codegen check` reads through
    // Python universal-newline translation and calls such a tree current; verified against
    // the real CLI, which reports "up to date" for exactly this mutation. Hashing raw bytes
    // instead would redden a consumer's CI on a tree the CLI passes.
    const crlf = (content: string): string => content.replace(/\n/g, "\r\n");
    const input = withEdit(withEdit(tsFixture(), "types.ts", crlf), "binder.ts", crlf);

    const report = await runCodegenCheck({ ...input, lockContent: crlf(input.lockContent) });

    expect(report.drifts).toEqual([]);
    expect(report.isCurrent).toBe(true);
  });

  it("still catches a hand edit inside a CRLF tree", async () => {
    // Normalizing line endings must not blunt the check itself: only the endings are
    // forgiven, never a changed byte below the stamp.
    const input = withEdit(tsFixture(), "types.ts", (content) =>
      handEdit(content, "export const HAND = 1;\n").replace(/\n/g, "\r\n"),
    );

    const report = await runCodegenCheck(input);

    expect(report.drifts.map((drift) => [drift.path, drift.category])).toEqual([
      ["types.ts", "hand-edited"],
    ]);
  });

  it("reports a stamped file the lock does not track as `orphan`", async () => {
    const stray = { path: "stale.ts", content: contentOf(tsFixture(), "types.ts") };

    const report = await runCodegenCheck(plus(tsFixture(), stray));

    expect(report.drifts).toEqual([
      {
        path: "stale.ts",
        category: "orphan",
        detail: "Stamped generated file not tracked by the lock — stale; remove or regenerate.",
      },
    ]);
  });

  it("reports a stray whose stamp is corrupt below the begin marker as an `orphan` all the same", async () => {
    // The orphan predicate is `has_stamp` (does the text OPEN with the begin marker),
    // not the full parse. A stronger predicate here would silently ignore precisely the
    // stale file the lock exists to catch.
    const stray = { path: "stale.ts", content: `// ${STAMP_BEGIN}\n// garbage, no end marker\n` };

    const report = await runCodegenCheck(plus(tsFixture(), stray));

    expect(report.drifts.map((drift) => [drift.path, drift.category])).toEqual([
      ["stale.ts", "orphan"],
    ]);
  });

  it("detects an orphan by the comment syntax of its own suffix", async () => {
    // A `#`-stamped stray in a TypeScript tree: the prefix comes from the file, not the target.
    const stray = { path: "stale.py", content: contentOf(pyFixture(), "models.py") };

    const report = await runCodegenCheck(plus(tsFixture(), stray));

    expect(report.drifts.map((drift) => [drift.path, drift.category])).toEqual([
      ["stale.py", "orphan"],
    ]);
  });
});

// ── Ordering ─────────────────────────────────────────────────────────────

describe("runCodegenCheck — drift ordering", () => {
  it("reports locked drifts first (sorted by path), then orphans (sorted by path)", async () => {
    const input = plus(
      withEdit(without(tsFixture(), "types.ts"), "binder.ts", (content) =>
        handEdit(content, "export const HAND = 1;\n"),
      ),
      { path: "zzz.ts", content: contentOf(tsFixture(), "types.ts") },
      { path: "aaa.py", content: contentOf(pyFixture(), "models.py") },
    );

    const report = await runCodegenCheck(input);

    // Consumers print this list, and tests depend on it, so the order is part of the contract.
    expect(report.drifts.map((drift) => [drift.path, drift.category])).toEqual([
      ["binder.ts", "hand-edited"],
      ["types.ts", "missing"],
      ["aaa.py", "orphan"],
      ["zzz.ts", "orphan"],
    ]);
  });
});

// ── Files the check leaves alone ─────────────────────────────────────────

describe("runCodegenCheck — files outside the artifact set", () => {
  it("ignores an unstamped file of a stampable type", async () => {
    const input = plus(tsFixture(), { path: "notes.ts", content: "// just a note\n" });

    const report = await runCodegenCheck(input);

    expect(report.isCurrent).toBe(true);
  });

  it("ignores a file whose suffix is not stampable, even if it opens like a stamp", async () => {
    // The suffix gate comes FIRST — a consumer parks sidecars (a `sources.json`, say)
    // beside the lock, and an unknown suffix has no comment syntax to test against.
    const input = plus(tsFixture(), {
      path: "sources.json",
      content: `// ${STAMP_BEGIN}\n{}\n`,
    });

    const report = await runCodegenCheck(input);

    expect(report.isCurrent).toBe(true);
  });

  it("ignores a nested unstamped file", async () => {
    const input = plus(tsFixture(), {
      path: "nested/dir/helper.ts",
      content: "export const x = 1;\n",
    });

    const report = await runCodegenCheck(input);

    expect(report.isCurrent).toBe(true);
  });
});

// ── No verdict: a malformed lock or an unsafe path ───────────────────────

describe("runCodegenCheck — no-verdict conditions", () => {
  it("throws on a lock that is not TOML", async () => {
    await expect(
      runCodegenCheck({ lockContent: "this is not [[[ toml", files: [] }),
    ).rejects.toThrow(CodegenLockError);
  });

  it("throws on a lock missing a header field", async () => {
    await expect(
      runCodegenCheck({ lockContent: 'engine_version = "0.0.0"\n', files: [] }),
    ).rejects.toThrow(/crate_fingerprint/);
  });

  it("throws on an unknown key — the lock's shape is the contract, not a superset", async () => {
    await expect(
      runCodegenCheck({ lockContent: lockWith('extra = "surprise"\n'), files: [] }),
    ).rejects.toThrow(/unexpected key 'extra'/);

    await expect(
      runCodegenCheck({
        lockContent: lockWith(`${artifactEntry(tomlLiteral("types.ts"))}mode = "surprise"\n`),
        files: [],
      }),
    ).rejects.toThrow(/unexpected key 'mode'/);
  });

  it.each([
    ["absolute", tomlLiteral("/types.ts"), /absolute paths and drive prefixes/],
    ["drive-prefixed", tomlLiteral("C:/types.ts"), /absolute paths and drive prefixes/],
    ["backslashed", tomlLiteral("sub\\types.ts"), /backslashes are not allowed/],
    // A basic string here, so TOML decodes the escape into a real U+0001 in the path.
    ["control-charactered", '"ty\\u0001pes.ts"', /control characters are not allowed/],
    ["parent-escaping", tomlLiteral("../types.ts"), /path components are not allowed/],
    ["dot-prefixed", tomlLiteral("./types.ts"), /path components are not allowed/],
    ["empty", tomlLiteral(""), /path is empty/],
    ["wrong-suffixed", tomlLiteral("notes.txt"), /unsupported artifact suffix/],
  ])("throws on a %s artifact path in the lock", async (_label, tomlPath, reason) => {
    const check = runCodegenCheck({ lockContent: lockWith(artifactEntry(tomlPath)), files: [] });

    await expect(check).rejects.toThrow(CodegenLockError);
    await expect(check).rejects.toThrow(reason);
  });

  it("throws on a duplicate artifact path in the lock", async () => {
    const lockContent = lockWith(
      artifactEntry(tomlLiteral("types.ts")) + artifactEntry(tomlLiteral("types.ts")),
    );

    await expect(runCodegenCheck({ lockContent, files: [] })).rejects.toThrow(
      /Duplicate artifact path/,
    );
  });

  it("throws on a non-canonical path in the supplied tree", async () => {
    // Left unchecked, `./types.ts` silently produces BOTH a `missing` and an `orphan`
    // for the same file — a wrong verdict, which is worse than a loud refusal.
    const input = withEdit(tsFixture(), "types.ts", (content) => content);
    const mangled: CodegenCheckInput = {
      ...input,
      files: input.files.map((file) =>
        file.path === "types.ts" ? { ...file, path: "./types.ts" } : file,
      ),
    };

    await expect(runCodegenCheck(mangled)).rejects.toThrow(CodegenLockError);
  });

  it("throws on a duplicate path in the supplied tree", async () => {
    const input = tsFixture();
    const duplicated = plus(input, { path: "types.ts", content: contentOf(input, "types.ts") });

    await expect(runCodegenCheck(duplicated)).rejects.toThrow(/Duplicate artifact path/);
  });
});

// ── The walk helpers a caller filters with ───────────────────────────────

describe("the stampable-suffix surface", () => {
  it("names exactly the suffixes codegen stamps", () => {
    expect([...STAMPABLE_ARTIFACT_SUFFIXES]).toEqual([".py", ".ts"]);
  });

  it.each([
    ["types.ts", true],
    ["models.py", true],
    ["nested/dir/types.ts", true],
    ["sources.json", false],
    ["codegen.lock", false],
    ["README", false],
    [".ts", false],
  ])("classifies %s", (path, expected) => {
    expect(isStampableArtifactPath(path)).toBe(expected);
  });
});
